# Generated by Django 5.0.6 on 2024-07-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Views"),
        ),
    ]
